package model

import (
	"context"
	"errors"
	"regexp"
	"slices"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/QuantumNous/new-api/common"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

const BusinessMetadataContextKey = "business_metadata"
const BusinessModalitiesContextKey = "business_allowed_modalities"

var asyncSummaryReferencePattern = regexp.MustCompile(`(?i)(https?://|data:)[^\s"'<>\\]+`)

// SanitizeAsyncSummary keeps persistent diagnostics from becoming a second
// storage API for expiring generated bytes or upstream capability URLs.
func SanitizeAsyncSummary(value string) string {
	value = asyncSummaryReferencePattern.ReplaceAllString(value, "[result reference omitted]")
	runes := []rune(value)
	if len(runes) > 1024 {
		return string(runes[:1024]) + " [truncated]"
	}
	return value
}

// BusinessScope is an exact account-and-label domain. Empty labels are values,
// never wildcards. Keys can rotate without changing the domain of older tasks.
type BusinessScope struct {
	UserID    int
	TagLevel1 string
	TagLevel2 string
}

type BusinessMetadata struct {
	BusinessSystemID string `json:"business_system_id,omitempty" gorm:"type:varchar(128);default:'';index"`
	TagLevel1        string `json:"tag_level_1" gorm:"column:tag_level_1;type:varchar(64);default:'';index"`
	TagLevel2        string `json:"tag_level_2" gorm:"column:tag_level_2;type:varchar(64);default:'';index"`
	BusinessID       string `json:"business_id,omitempty" gorm:"type:varchar(128);default:'';index"`
	ExternalUserID   string `json:"external_user_id,omitempty" gorm:"type:varchar(128);default:'';index"`
	ExternalTaskID   string `json:"external_task_id,omitempty" gorm:"type:varchar(128);default:'';index"`
	AsyncTaskID      string `json:"async_task_id,omitempty" gorm:"type:varchar(64);default:'';index"`
}

func NormalizeBusinessIdentifier(value string, maxRunes int) (string, error) {
	value = strings.TrimSpace(value)
	if !utf8.ValidString(value) || utf8.RuneCountInString(value) > maxRunes || strings.ContainsFunc(value, unicode.IsControl) {
		return "", errors.New("invalid business identifier")
	}
	return value, nil
}

func NormalizeBusinessModalities(values []string) ([]string, error) {
	result := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if !slices.Contains([]string{"text", "image", "video", "audio"}, value) {
			return nil, errors.New("allowed_modalities must contain text, image, video or audio")
		}
		if !slices.Contains(result, value) {
			result = append(result, value)
		}
	}
	return result, nil
}

func (token *Token) GetAllowedModalities() ([]string, error) {
	if token.AllowedModalities == "" {
		return []string{}, nil
	}
	var values []string
	if err := common.UnmarshalJsonStr(token.AllowedModalities, &values); err != nil {
		return nil, err
	}
	return NormalizeBusinessModalities(values)
}

func (token *Token) SetAllowedModalities(values []string) error {
	values, err := NormalizeBusinessModalities(values)
	if err != nil {
		return err
	}
	if len(values) == 0 {
		token.AllowedModalities = ""
		return nil
	}
	encoded, err := common.Marshal(values)
	if err != nil {
		return err
	}
	token.AllowedModalities = string(encoded)
	return nil
}

func SetBusinessMetadata(c *gin.Context, metadata BusinessMetadata) {
	c.Set(BusinessMetadataContextKey, metadata)
}

func BusinessMetadataFromContext(c *gin.Context) BusinessMetadata {
	metadata, _ := c.Get(BusinessMetadataContextKey)
	result, _ := metadata.(BusinessMetadata)
	if id := c.GetString("async_job_id"); id != "" {
		result.AsyncTaskID = id
	}
	return result
}

func BusinessScopeFromContext(c *gin.Context) BusinessScope {
	metadata := BusinessMetadataFromContext(c)
	return BusinessScope{UserID: c.GetInt("id"), TagLevel1: metadata.TagLevel1, TagLevel2: metadata.TagLevel2}
}

func TaskAccessibleInBusinessScope(c *gin.Context, task *Task) bool {
	if task == nil {
		return false
	}
	// Job-backed native results are internal execution state, not a second
	// download API. Only the trusted in-process worker can archive them; all
	// external clients must use the scoped, expiring async object endpoints.
	if task.AsyncJobID != "" && !InternalAsyncTaskAccess(c, task.AsyncJobID) {
		return false
	}
	return BusinessScopeAccessible(c, task.UserId, task.BusinessMetadata)
}

type internalAsyncTaskAccessKey struct{}

// SetInternalAsyncTaskAccess must only be called after authentication verifies
// a server-created execution context. Client headers never grant this access.
func SetInternalAsyncTaskAccess(c *gin.Context, jobID string) {
	c.Request = c.Request.WithContext(context.WithValue(c.Request.Context(), internalAsyncTaskAccessKey{}, jobID))
}

func InternalAsyncTaskAccess(c *gin.Context, jobID string) bool {
	trusted, _ := c.Request.Context().Value(internalAsyncTaskAccessKey{}).(string)
	return jobID != "" && trusted == jobID
}

func BusinessScopeAccessible(c *gin.Context, userID int, metadata BusinessMetadata) bool {
	if userID != c.GetInt("id") {
		return false
	}
	// Browser sessions and dashboard PATs administer all domains of their account.
	if c.GetInt("token_id") == 0 {
		return true
	}
	scope := BusinessScopeFromContext(c)
	return metadata.TagLevel1 == scope.TagLevel1 && metadata.TagLevel2 == scope.TagLevel2
}

// ApplyBusinessScope keeps label comparisons case-sensitive on MySQL too.
func ApplyBusinessScope(query *gorm.DB, scope BusinessScope) *gorm.DB {
	query = query.Where("user_id = ?", scope.UserID)
	for _, field := range []struct{ name, value string }{{"tag_level_1", scope.TagLevel1}, {"tag_level_2", scope.TagLevel2}} {
		if common.UsingMainDatabase(common.DatabaseTypeMySQL) {
			query = query.Where("BINARY COALESCE("+field.name+", '') = BINARY ?", field.value)
		} else {
			query = query.Where("COALESCE("+field.name+", '') = ?", field.value)
		}
	}
	return query
}

func UpdateBusinessSystemID(userID int, value string) error {
	value, err := NormalizeBusinessIdentifier(value, 128)
	if err != nil {
		return err
	}
	if err := DB.Model(&User{}).Where("id = ?", userID).Update("business_system_id", value).Error; err != nil {
		return err
	}
	return invalidateUserCache(userID)
}

type BusinessLogFilter map[string]string

func ApplyBusinessFilters(query *gorm.DB, filters BusinessLogFilter, logDatabase bool) *gorm.DB {
	for _, column := range []string{"tag_level_1", "tag_level_2", "business_system_id", "business_id", "external_user_id", "external_task_id", "async_task_id"} {
		value, present := filters[column]
		if !present {
			continue
		}
		mysql := common.UsingMainDatabase(common.DatabaseTypeMySQL)
		if logDatabase {
			mysql = common.UsingLogDatabase(common.DatabaseTypeMySQL)
		}
		if mysql {
			query = query.Where("BINARY COALESCE("+column+", '') = BINARY ?", value)
		} else {
			query = query.Where("COALESCE("+column+", '') = ?", value)
		}
	}
	return query
}
